substitutions:
  devicename: esp32-micradar
  upper_devicename: ESP32 Radar

esphome:
  name: ${devicename}
  friendly_name: ${upper_devicename}
  comment: ${upper_devicename}
  name_add_mac_suffix: false

esp32:
  board: m5stack-atom

external_components:
  - source: github://tsunglung/esphome-micradar@master
    components: [ micradar ]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${devicename}
    password: "12345678"

captive_portal:

#web_server:

# Enable logging
logger:
#  level: VERY_VERBOSE

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:
  - platform: esphome


uart:
 rx_pin: GPIO21
 tx_pin: GPIO25
 baud_rate: 115200

micradar:
  model: "R60ABD1"

binary_sensor:
  - platform: status
    name: "Status"
  - platform: micradar
    has_target:
      name: "Presence Information"

button:
  - platform: safe_mode
    name: Safe Mode Boot
    entity_category: diagnostic
  - platform: restart
    name: "Restart"

  - platform: micradar
    get_radar_parameters:
      name: "Get Radar Parameters"
    factory_reset:
      name: "Factory Reset"

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: 27
    num_leds: 1
    rgb_order: GRB
    id: status_led
    name: Light
    effects:
      - random:
      - flicker:
      - addressable_rainbow:


select:
  - platform: micradar
    sleep_roll_over:
      name: "Sleep Roll Over Sensitivity"

sensor:
  - platform: uptime
    name: Uptime
    filters:
      - lambda: return x / 3600;
    unit_of_measurement: "h"
    accuracy_decimals: 1
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifisignal
    update_interval: 60s

  - platform: micradar
    movement_signs:
      name: "Body Movement Parameter"
    breathe_rate:
      name: "Breathe Rate"
    heartbeat_rate:
      name: "HeartBeat Rate"
    bed_status:
      name: "Bed Status"
    wake_up:
      name: "Wake up"
    light_sleep:
      name: "Light Sleep"
    deep_sleep:
      name: "Deep Sleep"
    sleep_quality:
      name: "Sleep Quality"
    distance:
      name: "Distance"
    x:
      name: "X"
    y:
      name: "Y"
    z:
      name: "Z"

switch:
  - platform: micradar
    human_exist:
      name: "Human Exist Monitor"
    human_breath:
      name: "Human Brethe Monitor"
    human_heart_monitor:
      name: "Human Heart Montior"
    human_sleep_monitor:
      name: "Human Sleep Montior"

text_sensor:
  - platform: version
    name: "ESPHome Version"
  - platform: wifi_info
    ip_address:
      name: "IP Address"

  - platform: micradar
    equipment_state:
      name: "Equipment State"
    product_model:
      name: "Product Model"
    product_id:
      name: "Product ID"
    hardware_model:
      name: "Hardware Model"
    hardware_version:
      name: "Hardware Version"
    motion_status:
      name: "Motion Information"
    sleep_status:
      name: "Sleep Status"
    sleep_quality_level:
      name: "Sleep Quality Level"
    sleep_total_status:
      name: "Sleep Total Status"

time:
  - platform: homeassistant
    id: homeassistant_time
